apiVersion: v1
kind: Service
metadata:
  name: quick-server-service
  namespace: quick-server
spec:
  selector:
    app: quick-server
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  ClusterIP: None
